"""el plan dramatico del capitulo se persiste

Revision ID: 3a4922315ff2
Revises: ee2b1ecf97e0
Create Date: 2026-09-23 23:59:20.147315

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3a4922315ff2"
down_revision: str | Sequence[str] | None = "ee2b1ecf97e0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Los cuatro `CheckConstraint` van a mano: `--autogenerate` los emite con
    # la tabla cuando es NUEVA, y `capitulo` ya existia. Lo dejo anotado T2 en
    # Desviaciones al cerrar la ola 1, y aqui es donde mordia.
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("capitulo", schema=None) as batch_op:
        batch_op.add_column(sa.Column("lugar", sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column("objetivo", sa.String(length=500), nullable=False))
        batch_op.add_column(sa.Column("obstaculo", sa.String(length=500), nullable=False))
        batch_op.add_column(
            sa.Column("giro_de_valor_previsto", sa.String(length=200), nullable=False)
        )

        batch_op.create_check_constraint("ck_capitulo_lugar_no_vacio", "length(trim(lugar)) > 0")
        batch_op.create_check_constraint(
            "ck_capitulo_objetivo_no_vacio", "length(trim(objetivo)) > 0"
        )
        batch_op.create_check_constraint(
            "ck_capitulo_obstaculo_no_vacio", "length(trim(obstaculo)) > 0"
        )
        batch_op.create_check_constraint(
            "ck_capitulo_giro_de_valor_previsto_no_vacio",
            "length(trim(giro_de_valor_previsto)) > 0",
        )


def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table("capitulo", schema=None) as batch_op:
        batch_op.drop_constraint("ck_capitulo_lugar_no_vacio", type_="check")
        batch_op.drop_constraint("ck_capitulo_objetivo_no_vacio", type_="check")
        batch_op.drop_constraint("ck_capitulo_obstaculo_no_vacio", type_="check")
        batch_op.drop_constraint("ck_capitulo_giro_de_valor_previsto_no_vacio", type_="check")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("capitulo", schema=None) as batch_op:
        batch_op.drop_column("giro_de_valor_previsto")
        batch_op.drop_column("obstaculo")
        batch_op.drop_column("objetivo")
        batch_op.drop_column("lugar")

    # ### end Alembic commands ###
