"""la deuda de la fase 2: seis columnas, una tabla y las variantes de un nombre

Revision ID: 4fddbbc8d61b
Revises: 3a4922315ff2
Create Date: 2026-09-24 02:02:08.866276

**Una sola migracion para las cinco deudas de esquema**, que es la regla 2 del
reparto de la Fase 3: `--autogenerate` lee `Base.metadata` entera y dos agentes
generando a la vez producen dos *heads*.

**Y tres cosas se escriben a mano, porque `--autogenerate` no las emite:**

1. Los `CheckConstraint` sobre `capitulo` y `hecho_canon`. Alembic los compara
   cuando la tabla es **nueva** -- el de `variante_de_nombre` si salio solo -- y
   no cuando ya existe. Lo dejo escrito T2 de la Fase 2 y aqui volvio a morder:
   se comprobo ejecutandolo, y sin estas lineas la base migrada se quedaba sin
   las dos restricciones mientras la de `create_all` las tenia.
2. El `server_default` de `ejecucion.ids_por_capa`. Es `NOT NULL` y la tabla
   puede tener filas: sin un valor de partida, el modo batch recrea la tabla y
   las filas viejas entran con `NULL`. `'{}'` es lo que significa «no entro
   nada con identificador», que es la verdad de una fila anterior a esta
   columna.
3. Los nombres de las claves ajenas. En modo batch **toda restriccion necesita
   nombre**, o muere con «Constraint must have a name».
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4fddbbc8d61b"
down_revision: str | Sequence[str] | None = "3a4922315ff2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Los diez beats de `definitions.md` §6. Van escritos y no importados de
# `features/outline/schemas.py` a proposito: una migracion describe el esquema
# **de su momento**, y si el enumerado crece manana esta sentencia tiene que
# seguir diciendo lo que aplico hoy.
_BEATS = (
    "presentacion_de_carencias",
    "encuentro",
    "punto_de_no_retorno",
    "diversion_y_juegos",
    "punto_medio",
    "la_grieta",
    "ruptura",
    "revelacion_interior",
    "gran_gesto",
    "hea_hfn",
)
_BEATS_EN_LISTA = ", ".join(f"'{beat}'" for beat in _BEATS)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "variante_de_nombre",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("obra_id", sa.Integer(), nullable=False),
        sa.Column("forma_canonica", sa.String(length=120), nullable=False),
        sa.Column("variante", sa.String(length=120), nullable=False),
        sa.CheckConstraint("length(trim(variante)) > 0", name="ck_variante_de_nombre_no_vacia"),
        sa.ForeignKeyConstraint(["obra_id"], ["obra.id"], name="fk_variante_de_nombre_obra_id"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("obra_id", "forma_canonica", "variante", name="uq_variante_de_nombre"),
    )
    with op.batch_alter_table("capitulo", schema=None) as batch_op:
        batch_op.add_column(sa.Column("beat_de_genero", sa.String(length=120), nullable=True))
        batch_op.create_check_constraint(
            "ck_capitulo_beat_de_genero",
            f"beat_de_genero IS NULL OR beat_de_genero IN ({_BEATS_EN_LISTA})",
        )

    with op.batch_alter_table("ejecucion", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("ids_por_capa", sa.JSON(), nullable=False, server_default=sa.text("'{}'"))
        )

    with op.batch_alter_table("hecho_canon", schema=None) as batch_op:
        batch_op.add_column(sa.Column("sustituye_a", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_hecho_canon_sustituye_a", "hecho_canon", ["sustituye_a"], ["id"]
        )
        batch_op.create_check_constraint(
            "ck_hecho_no_se_sustituye_a_si_mismo", "sustituye_a IS NULL OR sustituye_a <> id"
        )

    with op.batch_alter_table("trabajo", schema=None) as batch_op:
        batch_op.add_column(sa.Column("capitulo_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key("fk_trabajo_capitulo_id", "capitulo", ["capitulo_id"], ["id"])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("trabajo", schema=None) as batch_op:
        batch_op.drop_constraint("fk_trabajo_capitulo_id", type_="foreignkey")
        batch_op.drop_column("capitulo_id")

    with op.batch_alter_table("hecho_canon", schema=None) as batch_op:
        batch_op.drop_constraint("ck_hecho_no_se_sustituye_a_si_mismo", type_="check")
        batch_op.drop_constraint("fk_hecho_canon_sustituye_a", type_="foreignkey")
        batch_op.drop_column("sustituye_a")

    with op.batch_alter_table("ejecucion", schema=None) as batch_op:
        batch_op.drop_column("ids_por_capa")

    with op.batch_alter_table("capitulo", schema=None) as batch_op:
        batch_op.drop_constraint("ck_capitulo_beat_de_genero", type_="check")
        batch_op.drop_column("beat_de_genero")

    op.drop_table("variante_de_nombre")
    # ### end Alembic commands ###
