"""el esquema del juicio: rubrica, puntuacion y la latencia

Las cinco tablas de la Fase 6 y una columna, en **una sola migracion** (regla 2
del plan: el esquema tiene un solo dueno). Las tablas son nuevas, asi que no hay
filas que rellenar y el `upgrade` no necesita ir en pasos.

**`ejecucion.latencia_ms` entra nullable, y no es comodidad.** Las filas
anteriores a esta fase no tienen latencia y **no se puede inventar**: un cero
seria una medida falsa con aspecto de dato. El criterio es el de P-2 -si una
fila no se puede rellenar con un valor verdadero, no se rellena-, aplicado a una
columna en vez de a una tabla.

**Los `CheckConstraint` si salieron del `autogenerate` esta vez**, al contrario
de lo que paso en `544580bef1fe`. La diferencia es que alli se anadia una
restriccion a una tabla que ya existia y aqui viajan dentro de un `create_table`.
Se comprobaron leyendo el fichero, no dandolo por hecho.

Revision ID: 51f67bf629ce
Revises: 544580bef1fe
Create Date: 2026-09-24 17:40:04.276583

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "51f67bf629ce"
down_revision: str | Sequence[str] | None = "544580bef1fe"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rubrica",
        sa.Column("rubrica_id", sa.Integer(), nullable=False),
        sa.Column("version", sa.String(length=32), nullable=False),
        sa.Column("escala_minimo", sa.Integer(), nullable=False),
        sa.Column("escala_maximo", sa.Integer(), nullable=False),
        sa.CheckConstraint("escala_maximo > escala_minimo", name="ck_rubrica_escala"),
        sa.PrimaryKeyConstraint("rubrica_id"),
        sa.UniqueConstraint("version", name="uq_rubrica_version"),
    )
    op.create_table(
        "criterio_de_rubrica",
        sa.Column("criterio_id", sa.Integer(), nullable=False),
        sa.Column("rubrica_id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=64), nullable=False),
        sa.Column("definicion", sa.Text(), nullable=False),
        sa.Column("ancla_minimo", sa.Text(), nullable=False),
        sa.Column("ancla_maximo", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["rubrica_id"], ["rubrica.rubrica_id"], name="fk_criterio_de_rubrica_rubrica_id"
        ),
        sa.PrimaryKeyConstraint("criterio_id"),
        sa.UniqueConstraint("rubrica_id", "nombre", name="uq_criterio_rubrica_nombre"),
    )
    op.create_table(
        "revision_humana",
        sa.Column("revision_id", sa.Integer(), nullable=False),
        sa.Column("obra_id", sa.Integer(), nullable=False),
        sa.Column("rubrica_id", sa.Integer(), nullable=False),
        sa.Column("revisor", sa.String(length=64), nullable=False),
        sa.Column("fecha", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["rubrica_id"], ["rubrica.rubrica_id"], name="fk_revision_humana_rubrica_id"
        ),
        sa.PrimaryKeyConstraint("revision_id"),
    )
    op.create_table(
        "puntuacion",
        sa.Column("puntuacion_id", sa.Integer(), nullable=False),
        sa.Column("validador", sa.String(length=64), nullable=False),
        sa.Column("unidad", sa.String(length=32), nullable=False),
        sa.Column("unidad_id", sa.String(length=64), nullable=False),
        sa.Column("valor", sa.Float(), nullable=False),
        sa.Column("criterio_id", sa.Integer(), nullable=True),
        sa.Column("justificacion", sa.Text(), nullable=True),
        sa.Column("origen", sa.String(length=16), nullable=False),
        sa.CheckConstraint(
            "criterio_id IS NULL OR (justificacion IS NOT NULL AND trim(justificacion) <> '')",
            name="ck_puntuacion_justificacion",
        ),
        sa.CheckConstraint(
            "origen IN ('juez', 'humana', 'programatico', 'formal')", name="ck_puntuacion_origen"
        ),
        sa.ForeignKeyConstraint(
            ["criterio_id"], ["criterio_de_rubrica.criterio_id"], name="fk_puntuacion_criterio_id"
        ),
        sa.PrimaryKeyConstraint("puntuacion_id"),
    )
    op.create_table(
        "aceptacion_de_entrega",
        sa.Column("aceptacion_id", sa.Integer(), nullable=False),
        sa.Column("version_publicada_id", sa.Integer(), nullable=False),
        sa.Column("aceptada", sa.Boolean(), nullable=False),
        sa.Column("momento", sa.DateTime(timezone=True), nullable=False),
        sa.Column("comentario", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["version_publicada_id"],
            ["version_publicada.id"],
            name="fk_aceptacion_version_publicada_id",
        ),
        sa.PrimaryKeyConstraint("aceptacion_id"),
    )
    with op.batch_alter_table("ejecucion", schema=None) as batch_op:
        batch_op.add_column(sa.Column("latencia_ms", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ejecucion", schema=None) as batch_op:
        batch_op.drop_column("latencia_ms")

    op.drop_table("aceptacion_de_entrega")
    op.drop_table("puntuacion")
    op.drop_table("revision_humana")
    op.drop_table("criterio_de_rubrica")
    op.drop_table("rubrica")
    # ### end Alembic commands ###
