"""esquema de la fase 1

Revision ID: 7cbf6d625fae
Revises: 1cb7ac5fc2e9
Create Date: 2026-09-23 21:58:54.942244

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7cbf6d625fae"
down_revision: str | Sequence[str] | None = "1cb7ac5fc2e9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "destinatario",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=120), nullable=False),
        sa.Column("edad", sa.Integer(), nullable=False),
        sa.Column("rasgos", sa.JSON(), nullable=False),
        sa.Column("recuerdos", sa.JSON(), nullable=False),
        sa.Column("fecha_de_nacimiento", sa.Date(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "obra",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("titulo", sa.String(length=200), nullable=False),
        sa.Column("genero", sa.String(length=60), nullable=False),
        sa.Column("tono", sa.String(length=60), nullable=False),
        sa.Column("nivel_de_calor", sa.Integer(), nullable=False),
        sa.Column("destinatario_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["destinatario_id"],
            ["destinatario.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hecho_canon",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("obra_id", sa.Integer(), nullable=False),
        sa.Column("enunciado", sa.Text(), nullable=False),
        sa.Column("origen", sa.String(length=20), nullable=False),
        sa.Column("escena_de_origen", sa.String(length=60), nullable=True),
        sa.CheckConstraint(
            "(origen = 'escena' AND escena_de_origen IS NOT NULL) OR (origen <> 'escena' AND escena_de_origen IS NULL)",
            name="ck_hecho_origen_coherente",
        ),
        sa.ForeignKeyConstraint(
            ["obra_id"],
            ["obra.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "palabra_prohibida",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ambito", sa.String(length=10), nullable=False),
        sa.Column("termino", sa.String(length=200), nullable=False),
        sa.Column("obra_id", sa.Integer(), nullable=True),
        sa.Column("motivo", sa.String(length=500), nullable=True),
        sa.CheckConstraint(
            "ambito IN ('global', 'obra', 'brief')", name="ck_palabra_prohibida_ambito"
        ),
        sa.ForeignKeyConstraint(
            ["obra_id"],
            ["obra.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("palabra_prohibida")
    op.drop_table("hecho_canon")
    op.drop_table("obra")
    op.drop_table("destinatario")
    # ### end Alembic commands ###
