"""la entrevista, su texto aportado y los vetos del brief

Revision ID: 7e933775fe09
Revises: 0be0f5b9473d
Create Date: 2026-09-23 22:37:34.197228

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7e933775fe09"
down_revision: str | Sequence[str] | None = "0be0f5b9473d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "entrevista",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("respuestas", sa.JSON(), nullable=False),
        sa.Column("obra_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["obra_id"], ["obra.id"], name="fk_entrevista_obra_id"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "texto_aportado",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("entrevista_id", sa.Integer(), nullable=False),
        sa.Column("contenido", sa.Text(), nullable=False),
        sa.Column("procedencia", sa.String(length=60), nullable=False),
        sa.CheckConstraint("trim(contenido) <> ''", name="ck_texto_aportado_no_vacio"),
        sa.ForeignKeyConstraint(
            ["entrevista_id"], ["entrevista.id"], name="fk_texto_aportado_entrevista_id"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("texto_aportado")
    op.drop_table("entrevista")
    # ### end Alembic commands ###
