"""el hecho de canon toma la forma del documento, y recuerdos_aportados

Revision ID: 8b0c3ef6ccca
Revises: 7e933775fe09
Create Date: 2026-09-23 22:55:18.733662

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = "8b0c3ef6ccca"
down_revision: str | Sequence[str] | None = "7e933775fe09"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("destinatario", schema=None) as batch_op:
        batch_op.add_column(sa.Column("recuerdos_aportados", sa.JSON(), nullable=False))
        batch_op.drop_column("recuerdos")

    with op.batch_alter_table("hecho_canon", schema=None) as batch_op:
        batch_op.add_column(sa.Column("entidad", sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column("atributo", sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column("valor", sa.Text(), nullable=False))
        batch_op.add_column(sa.Column("confianza", sa.Float(), nullable=False))
        batch_op.drop_column("enunciado")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("hecho_canon", schema=None) as batch_op:
        batch_op.add_column(sa.Column("enunciado", sa.TEXT(), nullable=False))
        batch_op.drop_column("confianza")
        batch_op.drop_column("valor")
        batch_op.drop_column("atributo")
        batch_op.drop_column("entidad")

    with op.batch_alter_table("destinatario", schema=None) as batch_op:
        batch_op.add_column(sa.Column("recuerdos", sqlite.JSON(), nullable=False))
        batch_op.drop_column("recuerdos_aportados")

    # ### end Alembic commands ###
