"""Los tokens de cache de prompt se guardan, aunque todavia no se imputen

P-18. El CLI usa cache de prompt y `usage` traia dos campos que nadie leia. Una
medicion contra el proveedor con un prompt de 5.012 tokens devolvio
`input_tokens=10` y `cache_read_input_tokens=6835`: el coste imputado salia
corto por un factor de ~680 en esa llamada.

**Esta revision solo guarda el dato.** No toca `coste`, ni `tokens_reales`, ni
la tarifa: imputar la cache exige decidir a que precio, y eso lo firma una
persona. Lo que no se puede hacer despues es recuperar el dato de una corrida
que no lo guardo, y por eso la columna va primero y la decision despues.

**Nulables a proposito.** `NULL` es «no se sabe» —toda ejecucion anterior a
esta revision— y cero es una medicion: no hubo cache. Con `NOT NULL DEFAULT 0`
las filas viejas dirian que no hubo cache, que es una afirmacion que nadie ha
comprobado y que falsearia cualquier recalculo posterior.

Revision ID: 8bc0aee00b81
Revises: 9363ce839179
Create Date: 2026-09-24 16:12:20.269442

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8bc0aee00b81"
down_revision: str | Sequence[str] | None = "9363ce839179"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ejecucion", schema=None) as batch_op:
        batch_op.add_column(sa.Column("cache_read_input_tokens", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("cache_creation_input_tokens", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ejecucion", schema=None) as batch_op:
        batch_op.drop_column("cache_creation_input_tokens")
        batch_op.drop_column("cache_read_input_tokens")

    # ### end Alembic commands ###
