"""esquema de publicacion

Revision ID: 9363ce839179
Revises: 4fddbbc8d61b
Create Date: 2026-09-24 16:03:19.723881

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9363ce839179"
down_revision: str | Sequence[str] | None = "4fddbbc8d61b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dedicatoria",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("obra_id", sa.Integer(), nullable=False),
        sa.Column("texto", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["obra_id"], ["obra.id"], name="fk_dedicatoria_obra_id"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("obra_id"),
    )
    op.create_table(
        "version_publicada",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("obra_id", sa.Integer(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("publicada_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sucede_a_id", sa.Integer(), nullable=True),
        sa.Column("identificador_publico", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(["obra_id"], ["obra.id"], name="fk_version_publicada_obra_id"),
        sa.ForeignKeyConstraint(
            ["sucede_a_id"], ["version_publicada.id"], name="fk_version_publicada_sucede_a_id"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("obra_id", "ordinal", name="uq_version_publicada_obra_ordinal"),
    )
    with op.batch_alter_table("version_publicada", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_version_publicada_identificador_publico"),
            ["identificador_publico"],
            unique=True,
        )

    op.create_table(
        "cuadro_de_defectos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("version_id", sa.Integer(), nullable=False),
        sa.Column("defectos", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["version_id"], ["version_publicada.id"], name="fk_cuadro_de_defectos_version_id"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("version_id"),
    )
    op.create_table(
        "ficha_de_lectura",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("version_id", sa.Integer(), nullable=False),
        sa.Column("entradas", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["version_id"], ["version_publicada.id"], name="fk_ficha_de_lectura_version_id"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("version_id"),
    )
    op.create_table(
        "capitulo_publicado",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("version_id", sa.Integer(), nullable=False),
        sa.Column("numero", sa.Integer(), nullable=False),
        sa.Column("titulo", sa.String(length=200), nullable=True),
        sa.Column("version_texto_id", sa.Integer(), nullable=False),
        sa.Column("cambiado", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["version_id"], ["version_publicada.id"], name="fk_capitulo_publicado_version_id"
        ),
        sa.ForeignKeyConstraint(
            ["version_texto_id"],
            ["version_texto.id"],
            name="fk_capitulo_publicado_version_texto_id",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("version_id", "numero", name="uq_capitulo_publicado_version_numero"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("capitulo_publicado")
    op.drop_table("ficha_de_lectura")
    op.drop_table("cuadro_de_defectos")
    with op.batch_alter_table("version_publicada", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_version_publicada_identificador_publico"))

    op.drop_table("version_publicada")
    op.drop_table("dedicatoria")
    # ### end Alembic commands ###
