"""intentos descartados: la evidencia de la escalada (P-20)

Plan 8, T4. Tabla **nueva y aparte**: la `version_texto` del intento rechazado
se sigue borrando por R-7, y lo que queda para decidir -texto, codigos y citas,
termino vetado- vive aqui, fuera de lo vigente. Ningun lector del paquete mira
esta tabla, asi que no puede contaminar el capitulo siguiente.

Sin `sqlite-vec` de por medio: no hay columna vectorial, la migracion es la
misma con y sin la extension.

Revision ID: b85921f41873
Revises: 51f67bf629ce
Create Date: 2026-09-24 17:59:35.381286

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b85921f41873"
down_revision: str | Sequence[str] | None = "51f67bf629ce"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "intento_descartado",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("trabajo_id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.String(length=60), nullable=False),
        sa.Column("escena_id", sa.Integer(), nullable=False),
        sa.Column("numero", sa.Integer(), nullable=False),
        sa.Column("texto", sa.Text(), nullable=False),
        sa.Column("defectos", sa.JSON(), nullable=False),
        sa.Column("termino_vetado", sa.String(length=200), nullable=True),
        sa.Column("creado_en", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["escena_id"], ["escena.id"], name="fk_intento_descartado_escena_id"
        ),
        sa.ForeignKeyConstraint(
            ["trabajo_id"], ["trabajo.id"], name="fk_intento_descartado_trabajo_id"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("intento_descartado", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_intento_descartado_run_id"), ["run_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_intento_descartado_trabajo_id"), ["trabajo_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("intento_descartado", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_intento_descartado_trabajo_id"))
        batch_op.drop_index(batch_op.f("ix_intento_descartado_run_id"))

    op.drop_table("intento_descartado")
    # ### end Alembic commands ###
