"""causa_fallo cabe: de String(60) a String(200)

Plan 8, T4, paso 7. El motivo del escalado («agotadas las 2 reparaciones
dirigidas; sigue bloqueado por EST-02») mide 65 caracteres, mas si nombra
varios codigos o la palabra vetada. SQLite no impone la longitud, asi que no se
truncaba nada: **la columna mentia**, y en cualquier otro motor habria cortado
el diagnostico. El modo batch recrea `trabajo`; se comprobo que sus tres
`CheckConstraint` y su indice sobreviven.

Revision ID: c24bf74a966c
Revises: b85921f41873
Create Date: 2026-09-24 18:04:55.499957

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c24bf74a966c"
down_revision: str | Sequence[str] | None = "b85921f41873"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("trabajo", schema=None) as batch_op:
        batch_op.alter_column(
            "causa_fallo",
            existing_type=sa.VARCHAR(length=60),
            type_=sa.String(length=200),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("trabajo", schema=None) as batch_op:
        batch_op.alter_column(
            "causa_fallo",
            existing_type=sa.String(length=200),
            type_=sa.VARCHAR(length=60),
            existing_nullable=True,
        )

    # ### end Alembic commands ###
