"""el esquema de la fase 2: capitulo, escena, texto, ledger y ejecuciones

Revision ID: ee2b1ecf97e0
Revises: 8b0c3ef6ccca
Create Date: 2026-09-23 23:29:08.664215

Las doce tablas de la fase entran **juntas y en una sola migracion** (regla 2
del reparto del plan 2): `--autogenerate` lee `Base.metadata` entera, y dos
agentes generando a la vez producen dos *heads*.

Tres cosas de este fichero no salieron de `--autogenerate`, y conviene decir
cuales para que nadie las borre pensando que sobran:

1. **Los `import` de `alembic/env.py`.** Entran en este mismo commit. Sin ellos
   `--autogenerate` no ve las tablas nuevas y, peor, ve como sobrantes las que
   ya estan en la base: la siguiente migracion habria sido el `drop_table` de
   las ocho de la Fase 1. Se comprobo ejecutandolo.
2. **Los `CheckConstraint` si estan.** No es contradictorio con lo que anoto la
   Fase 1: `--autogenerate` no **compara** restricciones de comprobacion, asi
   que una anadida a una tabla que ya existe no sale sola; pero una tabla NUEVA
   se emite con su `__table_args__` entero, y las doce son nuevas. Verificado
   leyendo el esquema de la base migrada, no fiandose de esta linea.
3. **Los disparadores y las vistas de abajo los escribio una persona.**
   `Base.metadata` no los contiene -- los emite un `after_create` -- y
   `--autogenerate` no los mira. El mismo SQL vive en `features/canon/modelos.py`
   y `features/escritura/modelos.py`, y `features/canon/tests/test_esquema_migrado.py`
   comprueba que los dos esquemas coinciden: son dos y solo uno existira.

Todas las claves ajenas van **nombradas**. SQLite no altera tablas: la primera
migracion que toque una de estas la recreara en modo batch, y ahi una
restriccion anonima muere con «Constraint must have a name».
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ee2b1ecf97e0"
down_revision: str | Sequence[str] | None = "8b0c3ef6ccca"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "capitulo",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("obra_id", sa.Integer(), nullable=False),
        sa.Column("numero", sa.Integer(), nullable=False),
        sa.Column("titulo", sa.String(length=200), nullable=True),
        sa.Column("pov_dominante", sa.String(length=120), nullable=False),
        sa.Column("gancho_de_apertura", sa.String(length=500), nullable=False),
        sa.Column("tipo_de_corte_final", sa.String(length=60), nullable=False),
        sa.Column("extension_objetivo", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "extension_objetivo BETWEEN 1000 AND 1500", name="ck_capitulo_extension_objetivo"
        ),
        sa.ForeignKeyConstraint(["obra_id"], ["obra.id"], name="fk_capitulo_obra_id"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("obra_id", "numero", name="uq_capitulo_obra_numero"),
    )
    op.create_table(
        "version_obra",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("obra_id", sa.Integer(), nullable=False),
        sa.Column("numero", sa.Integer(), nullable=False),
        sa.Column("biblia", sa.JSON(), nullable=False),
        sa.Column("vigente_desde", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["obra_id"], ["obra.id"], name="fk_version_obra_obra_id"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("obra_id", "numero", name="uq_version_obra_obra_numero"),
    )
    op.create_table(
        "escena",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("capitulo_id", sa.Integer(), nullable=False),
        sa.Column("version_obra_id", sa.Integer(), nullable=False),
        sa.Column("orden_discurso", sa.Integer(), nullable=False),
        sa.Column("tiempo_historia", sa.String(length=120), nullable=False),
        sa.Column("elapsed_desde_anterior", sa.String(length=120), nullable=True),
        sa.Column("pov", sa.String(length=120), nullable=False),
        sa.Column("lugar", sa.String(length=200), nullable=False),
        sa.Column("presentes", sa.JSON(), nullable=False),
        sa.Column("mencionados", sa.JSON(), nullable=False),
        sa.Column("objetivo_del_pov", sa.String(length=500), nullable=False),
        sa.Column("obstaculo", sa.String(length=500), nullable=False),
        sa.Column("resultado", sa.String(length=20), nullable=False),
        sa.Column("valor_entrada", sa.String(length=120), nullable=False),
        sa.Column("valor_salida", sa.String(length=120), nullable=False),
        sa.Column("extension_objetivo", sa.Integer(), nullable=False),
        sa.Column("densidad_de_dialogo_objetivo", sa.Float(), nullable=False),
        sa.Column("distancia_psiquica", sa.Integer(), nullable=False),
        sa.Column("beat_de_genero", sa.String(length=120), nullable=True),
        sa.Column("planta", sa.JSON(), nullable=False),
        sa.Column("paga", sa.JSON(), nullable=False),
        sa.Column("revela", sa.JSON(), nullable=False),
        sa.CheckConstraint(
            "resultado IN ('si', 'no', 'si-pero', 'no-y-ademas')", name="ck_escena_resultado"
        ),
        sa.CheckConstraint("trim(pov) <> ''", name="ck_escena_pov_unico"),
        sa.CheckConstraint(
            "distancia_psiquica BETWEEN 1 AND 5", name="ck_escena_distancia_psiquica"
        ),
        sa.CheckConstraint("valor_entrada <> valor_salida", name="ck_escena_giro_de_valor"),
        sa.ForeignKeyConstraint(["capitulo_id"], ["capitulo.id"], name="fk_escena_capitulo_id"),
        sa.ForeignKeyConstraint(
            ["version_obra_id"], ["version_obra.id"], name="fk_escena_version_obra_id"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("capitulo_id", name="uq_escena_capitulo"),
    )
    op.create_table(
        "hecho_usado_en",
        sa.Column("hecho_canon_id", sa.Integer(), nullable=False),
        sa.Column("capitulo_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["capitulo_id"], ["capitulo.id"], name="fk_hecho_usado_en_capitulo_id"
        ),
        sa.ForeignKeyConstraint(
            ["hecho_canon_id"], ["hecho_canon.id"], name="fk_hecho_usado_en_hecho_canon_id"
        ),
        sa.PrimaryKeyConstraint("hecho_canon_id", "capitulo_id", name="pk_hecho_usado_en"),
    )
    op.create_table(
        "ejecucion",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.String(length=60), nullable=False),
        sa.Column("obra_id", sa.Integer(), nullable=False),
        sa.Column("escena_id", sa.Integer(), nullable=True),
        sa.Column("version_obra_id", sa.Integer(), nullable=True),
        sa.Column("prompt_id", sa.String(length=60), nullable=False),
        sa.Column("prompt_version", sa.String(length=20), nullable=False),
        sa.Column("prompt_hash", sa.String(length=64), nullable=False),
        sa.Column("modelo", sa.String(length=60), nullable=False),
        sa.Column("semilla", sa.Integer(), nullable=False),
        sa.Column("parametros", sa.JSON(), nullable=False),
        sa.Column("tokens_por_capa", sa.JSON(), nullable=False),
        sa.Column("tokens_previstos", sa.Integer(), nullable=False),
        sa.Column("tokens_reales", sa.Integer(), nullable=True),
        sa.Column("coste", sa.Float(), nullable=True),
        sa.Column("ids_recuperados", sa.JSON(), nullable=False),
        sa.Column("ids_canon", sa.JSON(), nullable=False),
        sa.Column("veredicto", sa.String(length=30), nullable=True),
        sa.Column("creado_en", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("tokens_previstos >= 0", name="ck_ejecucion_tokens_previstos"),
        sa.ForeignKeyConstraint(["escena_id"], ["escena.id"], name="fk_ejecucion_escena_id"),
        sa.ForeignKeyConstraint(["obra_id"], ["obra.id"], name="fk_ejecucion_obra_id"),
        sa.ForeignKeyConstraint(
            ["version_obra_id"], ["version_obra.id"], name="fk_ejecucion_version_obra_id"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("ejecucion", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_ejecucion_run_id"), ["run_id"], unique=False)

    op.create_table(
        "embedding",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("obra_id", sa.Integer(), nullable=False),
        sa.Column("escena_id", sa.Integer(), nullable=True),
        sa.Column("fragmento", sa.Text(), nullable=False),
        sa.Column("vector", sa.LargeBinary(), nullable=False),
        sa.Column("dimension", sa.Integer(), nullable=False),
        sa.Column("modelo", sa.String(length=60), nullable=False),
        sa.ForeignKeyConstraint(["escena_id"], ["escena.id"], name="fk_embedding_escena_id"),
        sa.ForeignKeyConstraint(["obra_id"], ["obra.id"], name="fk_embedding_obra_id"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "evento",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("obra_id", sa.Integer(), nullable=False),
        sa.Column("escena_id", sa.Integer(), nullable=True),
        sa.Column("descripcion", sa.Text(), nullable=False),
        sa.Column("tiempo_historia", sa.String(length=120), nullable=False),
        sa.Column("lugar", sa.String(length=200), nullable=True),
        sa.Column("participantes", sa.JSON(), nullable=False),
        sa.Column("testigos", sa.JSON(), nullable=False),
        sa.Column("causa", sa.JSON(), nullable=False),
        sa.Column("consecuencia", sa.JSON(), nullable=False),
        sa.Column("excluye", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["escena_id"], ["escena.id"], name="fk_evento_escena_id"),
        sa.ForeignKeyConstraint(["obra_id"], ["obra.id"], name="fk_evento_obra_id"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hilo_narrativo",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("obra_id", sa.Integer(), nullable=False),
        sa.Column("pregunta", sa.String(length=500), nullable=False),
        sa.Column("estado", sa.String(length=10), nullable=False),
        sa.Column("escena_de_apertura", sa.Integer(), nullable=True),
        sa.Column("escena_de_cierre", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "estado <> 'pagado' OR escena_de_cierre IS NOT NULL",
            name="ck_hilo_narrativo_pagado_con_cierre",
        ),
        sa.CheckConstraint(
            "estado IN ('abierto', 'pagado', 'vencido')", name="ck_hilo_narrativo_estado"
        ),
        sa.ForeignKeyConstraint(
            ["escena_de_apertura"], ["escena.id"], name="fk_hilo_narrativo_escena_de_apertura"
        ),
        sa.ForeignKeyConstraint(
            ["escena_de_cierre"], ["escena.id"], name="fk_hilo_narrativo_escena_de_cierre"
        ),
        sa.ForeignKeyConstraint(["obra_id"], ["obra.id"], name="fk_hilo_narrativo_obra_id"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "plantado",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("obra_id", sa.Integer(), nullable=False),
        sa.Column("descripcion", sa.String(length=500), nullable=False),
        sa.Column("importancia", sa.String(length=12), nullable=False),
        sa.Column("escena_de_origen", sa.Integer(), nullable=False),
        sa.Column("escena_de_pago_prevista", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "importancia IN ('alta', 'media', 'decorativa')", name="ck_plantado_importancia"
        ),
        sa.ForeignKeyConstraint(
            ["escena_de_origen"], ["escena.id"], name="fk_plantado_escena_de_origen"
        ),
        sa.ForeignKeyConstraint(
            ["escena_de_pago_prevista"], ["escena.id"], name="fk_plantado_escena_de_pago_prevista"
        ),
        sa.ForeignKeyConstraint(["obra_id"], ["obra.id"], name="fk_plantado_obra_id"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "trabajo",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("obra_id", sa.Integer(), nullable=False),
        sa.Column("escena_id", sa.Integer(), nullable=True),
        sa.Column("tipo", sa.String(length=30), nullable=False),
        sa.Column("estado", sa.String(length=20), nullable=False),
        sa.Column("intento", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.String(length=60), nullable=False),
        sa.Column("causa_fallo", sa.String(length=60), nullable=True),
        sa.Column("creado_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "estado IN ('PLANIFICANDO', 'ENSAMBLANDO', 'ESCRIBIENDO', 'VALIDANDO', 'REPARANDO', 'EXTRAYENDO', 'INTEGRADA', 'ESCALADA', 'FALLIDA', 'CANCELADA')",
            name="ck_trabajo_estado",
        ),
        sa.CheckConstraint(
            "tipo IN ('escribir_escena', 'auditar_manuscrito', 'replanificar_capitulo')",
            name="ck_trabajo_tipo",
        ),
        sa.CheckConstraint("intento BETWEEN 0 AND 2", name="ck_trabajo_intento"),
        sa.ForeignKeyConstraint(["escena_id"], ["escena.id"], name="fk_trabajo_escena_id"),
        sa.ForeignKeyConstraint(["obra_id"], ["obra.id"], name="fk_trabajo_obra_id"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("trabajo", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_trabajo_run_id"), ["run_id"], unique=False)

    op.create_table(
        "version_texto",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("escena_id", sa.Integer(), nullable=False),
        sa.Column("numero", sa.Integer(), nullable=False),
        sa.Column("texto", sa.Text(), nullable=False),
        sa.Column("vigente", sa.Boolean(), nullable=False),
        sa.Column("run_id", sa.String(length=60), nullable=False),
        sa.Column("creado_en", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["escena_id"], ["escena.id"], name="fk_version_texto_escena_id"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("escena_id", "numero", name="uq_version_texto_escena_numero"),
    )
    with op.batch_alter_table("version_texto", schema=None) as batch_op:
        batch_op.create_index(
            "uq_version_texto_vigente",
            ["escena_id"],
            unique=True,
            sqlite_where=sa.text("vigente = 1"),
        )

    op.create_table(
        "resumen_capitulo",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("capitulo_id", sa.Integer(), nullable=False),
        sa.Column("version_texto_id", sa.Integer(), nullable=True),
        sa.Column("texto", sa.Text(), nullable=False),
        sa.Column("hechos_establecidos", sa.JSON(), nullable=False),
        sa.Column("hilos_abiertos", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["capitulo_id"], ["capitulo.id"], name="fk_resumen_capitulo_capitulo_id"
        ),
        sa.ForeignKeyConstraint(
            ["version_texto_id"], ["version_texto.id"], name="fk_resumen_capitulo_version_texto_id"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("capitulo_id", name="uq_resumen_capitulo_capitulo"),
    )
    # ### end Alembic commands ###

    # --- Escrito a mano: ni los disparadores ni las vistas salen de
    # `--autogenerate`. Van al final porque leen tablas que las lineas de
    # arriba acaban de crear.

    # El ledger es *append-only* (RF-MEM-05) **en el esquema**. La Fase 1 dejo
    # el registro de auditoria con una funcion que se niega a borrar -- una
    # puerta con cartel -- y lo anoto en Desviaciones. Una funcion solo protege
    # de quien la llame; esto protege tambien del `UPDATE` suelto en una
    # consola.
    op.execute(
        """
        CREATE TRIGGER IF NOT EXISTS trg_evento_sin_update
        BEFORE UPDATE ON evento
        BEGIN
            SELECT RAISE(ABORT, 'El ledger es append-only: un evento no se actualiza.');
        END;
        """
    )
    op.execute(
        """
        CREATE TRIGGER IF NOT EXISTS trg_evento_sin_delete
        BEFORE DELETE ON evento
        BEGIN
            SELECT RAISE(ABORT, 'El ledger es append-only: un evento no se borra.');
        END;
        """
    )

    # RF-ESC-02: el texto entregado es inmutable. `BEFORE UPDATE OF ...` deja
    # libre `vigente`, que es justo lo que la regla manda cambiar al editar: un
    # disparador sobre la tabla entera prohibiria tambien la forma legitima.
    op.execute(
        """
        CREATE TRIGGER IF NOT EXISTS trg_version_texto_inmutable
        BEFORE UPDATE OF texto, numero, escena_id, run_id ON version_texto
        BEGIN
            SELECT RAISE(ABORT,
                'Una version de texto es inmutable: editar crea otra y marca la vigente.');
        END;
        """
    )

    # Las dos vistas derivadas (RF-MEM-03, RF-MEM-05, regla de dominio 3).
    # Son vistas y no tablas por una razon dura: escritas a mano serian una
    # segunda verdad sobre quien sabe que y sobre cuando paso cada cosa, y
    # divergirian del texto sin que nada lo detectara. Como vistas **no se
    # pueden escribir**, asi que la imposibilidad no depende de que nadie
    # escriba el repositorio que las tocaria.
    op.execute(
        """
        CREATE VIEW IF NOT EXISTS estado_en_t AS
        SELECT ev.obra_id      AS obra_id,
               t.value         AS personaje,
               ev.id           AS evento_id,
               ev.tiempo_historia AS tiempo_historia,
               esc.orden_discurso AS sabe_desde
        FROM evento ev
        JOIN json_each(ev.testigos) t
        LEFT JOIN escena esc ON esc.id = ev.escena_id;
        """
    )
    op.execute(
        """
        CREATE VIEW IF NOT EXISTS cronologia AS
        SELECT ev.id            AS evento_id,
               ev.obra_id       AS obra_id,
               ev.tiempo_historia AS tiempo_historia,
               ev.lugar         AS lugar,
               ev.participantes AS participantes,
               ev.testigos      AS testigos,
               ev.excluye       AS excluye,
               esc.orden_discurso AS orden_discurso
        FROM evento ev
        LEFT JOIN escena esc ON esc.id = ev.escena_id;
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # Primero lo escrito a mano, y en orden inverso: una vista que sobrevive a
    # su tabla queda rota, y un disparador sobre `evento` impediria el
    # `drop_table` de mas abajo en cuanto alguien anadiera un `DELETE` previo.
    op.execute("DROP VIEW IF EXISTS cronologia")
    op.execute("DROP VIEW IF EXISTS estado_en_t")
    op.execute("DROP TRIGGER IF EXISTS trg_version_texto_inmutable")
    op.execute("DROP TRIGGER IF EXISTS trg_evento_sin_delete")
    op.execute("DROP TRIGGER IF EXISTS trg_evento_sin_update")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("resumen_capitulo")
    with op.batch_alter_table("version_texto", schema=None) as batch_op:
        batch_op.drop_index("uq_version_texto_vigente", sqlite_where=sa.text("vigente = 1"))

    op.drop_table("version_texto")
    with op.batch_alter_table("trabajo", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_trabajo_run_id"))

    op.drop_table("trabajo")
    op.drop_table("plantado")
    op.drop_table("hilo_narrativo")
    op.drop_table("evento")
    op.drop_table("embedding")
    with op.batch_alter_table("ejecucion", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ejecucion_run_id"))

    op.drop_table("ejecucion")
    op.drop_table("hecho_usado_en")
    op.drop_table("escena")
    op.drop_table("version_obra")
    op.drop_table("capitulo")
    # ### end Alembic commands ###
